#!/bin/bash

echo "🎯 YOLO11n Segmentation Tester Demo"
echo "===================================="
echo ""
echo "✅ Your Streamlit app is ready!"
echo ""
echo "🌟 Features included:"
echo "  📤 Image upload interface"
echo "  🔍 Real-time segmentation processing"
echo "  🎨 Visual mask overlays with bounding boxes"
echo "  📊 Detection statistics and charts"
echo "  ⚙️ Adjustable confidence & IoU thresholds"
echo "  🗂️ Batch processing for multiple images"
echo "  📱 Mobile-responsive design"
echo ""
echo "🚀 To start the app:"
echo "  ./run_app.sh"
echo ""
echo "🌐 Or manually:"
echo "  source .venv/bin/activate"
echo "  streamlit run app.py"
echo ""
echo "📱 Then visit: http://localhost:8501"
echo ""
echo "💡 Pro Tips:"
echo "  • Upload clear, well-lit images for best results"
echo "  • Adjust confidence threshold (0.25 default) for more/fewer detections"
echo "  • Use IoU threshold (0.45 default) to control overlapping detections"
echo "  • Try the batch processing feature for multiple images"
echo ""
echo "🎉 Enjoy testing your YOLO11n segmentation model!"